name: Build and deploy server to GKE

on:
  push:
    branches:
    - master

env:
  # Datos GKE
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-north1-a

  # Datos del despliegue en k8s
  NAMESPACE_NAME: adm-3
  DEPLOYMENT_NAME: adm-server
  CONTAINER_NAME: adm-server
  IMAGE_NAME: docker.pkg.github.com/didream/adm-visualizacion-datos-iii/adm-server-3

  SECRET_GITHUB_REGISTRY: ${{ secrets.SECRET_GITHUB_REGISTRY }}

jobs:
  server_to_registry:
    name: Build and push Docker image to GitHub Packages and deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: server/etc/Dockerfile
          path: .
          repository: didream/adm-visualizacion-datos-iii/adm-server-3
          tag_with_sha: true
          tag_with_ref: true
          tags: ${{ github.sha }}

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Get the GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Create k8s resources of app
        run: |-
          kubectl create -f etc/k8s/01-namespace.yml || true
          cat etc/k8s/02-github-package-secret.yml | sed "s/<SECRET_GITHUB_REGISTRY>/$SECRET_GITHUB_REGISTRY/" | kubectl apply -f - || true
          kubectl create -f server/etc/k8s || true

      - name: Update container image
        run: |-
          kubectl set image deployment/"$DEPLOYMENT_NAME" "$CONTAINER_NAME"="$IMAGE_NAME":"${{ github.sha }}" -n "$NAMESPACE_NAME"